## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df_new = application_df.drop(columns=['EIN', 'NAME'])
application_df_new

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [6]:
# Determine the number of unique values in each column.
application_df_new.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df_new['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
application_df_new['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [11]:
# You may find it helpful to look at CLASSIFICATION value counts >1
greater_than_1_counts = application_df_new['CLASSIFICATION'].value_counts()[application_df_new['CLASSIFICATION'].value_counts() > 1]
greater_than_1_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = ['C7000','C1700','C4000','C5000','C1270','C2700','C2800','C7100','C1300','C1280','C1230','C1400','C7200','C2300','C1240','C8000','C7120','C1500','C1800','C6000','C1250','C8200','C1238','C1278','C1235','C1237','C7210','C2400','C1720','C4100','C1257','C1600','C1260','C2710','C0','C3200','C1234','C1246','C1267','C1256', 'C1370','C1236','C2190','C4200','C5200','C1248','C2600','C1580','C6100','C1820','C1900','C2570','C1570','C3700','C2500','C1283','C2380','C1732','C1728','C2170','C4120','C8210','C4500','C1245','C2561','C2150']

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [15]:
# Convert categorical data to numeric with `pd.get_dummies`
df_encoded = pd.get_dummies(application_df_new)
df_encoded

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [16]:
# Split our preprocessed data into our features and target arrays
x = df_encoded.drop(['IS_SUCCESSFUL'],axis=1)
y = df_encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

input_dim = X_train.shape[1]

nn = Sequential()

# First hidden layer
nn.add(Dense(80, input_dim = input_dim, activation='relu'))

# Second hidden layer
nn.add(Dense(30, activation='relu'))

# Output layer
nn.add(Dense(1, activation='sigmoid'))

In [26]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 80)                9360

 dense_7 (Dense)             (None, 30)                2430

 dense_8 (Dense)             (None, 1)                 31

=================================================================
Total params: 11821 (46.18 KB)
Trainable params: 11821 (46.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Ensure dtypes
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('int32')
y_test = y_test.astype('int32')

In [29]:
# Train the model
trainer = nn.fit(X_train, y_train,
                 epochs=100,
                 batch_size=32,
                 validation_data=(X_test, y_test),
                 verbose=1)

Epoch 1/100
858/858 [==============================] - 5s 4ms/step - loss: 30858.3301 - accuracy: 0.4845 - val_loss: 10961.5908 - val_accuracy: 0.4675
Epoch 2/100
858/858 [==============================] - 2s 2ms/step - loss: 38899.8125 - accuracy: 0.4975 - val_loss: 22802.3574 - val_accuracy: 0.4675
Epoch 3/100
858/858 [==============================] - 2s 3ms/step - loss: 47473.4414 - accuracy: 0.5078 - val_loss: 1107.3042 - val_accuracy: 0.5325
Epoch 4/100
858/858 [==============================] - 2s 3ms/step - loss: 15153.0957 - accuracy: 0.5001 - val_loss: 1364.5677 - val_accuracy: 0.5325
Epoch 5/100
858/858 [==============================] - 2s 3ms/step - loss: 13681.9443 - accuracy: 0.5065 - val_loss: 217811.6875 - val_accuracy: 0.5325
Epoch 6/100
858/858 [==============================] - 3s 4ms/step - loss: 46280.3398 - accuracy: 0.5303 - val_loss: 2199.1399 - val_accuracy: 0.4675
Epoch 7/100
858/858 [==============================] - 3s 3ms/step - loss: 34127.9883 - accuracy: 0.5254 - val_loss: 9296.3525 - val_accuracy: 0.5325
Epoch 8/100
858/858 [==============================] - 2s 3ms/step - loss: 16488.2012 - accuracy: 0.5423 - val_loss: 27294.7188 - val_accuracy: 0.4675
Epoch 9/100
858/858 [==============================] - 2s 3ms/step - loss: 6721.0625 - accuracy: 0.5025 - val_loss: 1231.6702 - val_accuracy: 0.6443
Epoch 10/100
858/858 [==============================] - 2s 3ms/step - loss: 22246.9043 - accuracy: 0.5271 - val_loss: 1975.3995 - val_accuracy: 0.4675
Epoch 11/100
858/858 [==============================] - 2s 3ms/step - loss: 6767.2036 - accuracy: 0.5037 - val_loss: 4458.5825 - val_accuracy: 0.5325
Epoch 12/100
858/858 [==============================] - 4s 4ms/step - loss: 4151.4536 - accuracy: 0.5138 - val_loss: 634.4399 - val_accuracy: 0.4675
Epoch 13/100
858/858 [==============================] - 2s 3ms/step - loss: 2883.0806 - accuracy: 0.5175 - val_loss: 1731.0006 - val_accuracy: 0.4675
Epoch 14/100
858/858 [==============================] - 2s 2ms/step - loss: 1173.7341 - accuracy: 0.4987 - val_loss: 131.1933 - val_accuracy: 0.5153
Epoch 15/100
858/858 [==============================] - 2s 2ms/step - loss: 728.1042 - accuracy: 0.4981 - val_loss: 983.3566 - val_accuracy: 0.5325
Epoch 16/100
858/858 [==============================] - 2s 3ms/step - loss: 388.0526 - accuracy: 0.5188 - val_loss: 15.3597 - val_accuracy: 0.5325
Epoch 17/100
858/858 [==============================] - 3s 4ms/step - loss: 49.7506 - accuracy: 0.5256 - val_loss: 0.9815 - val_accuracy: 0.5348
Epoch 18/100
858/858 [==============================] - 2s 3ms/step - loss: 19.5781 - accuracy: 0.6055 - val_loss: 0.6329 - val_accuracy: 0.6500
Epoch 19/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6307 - accuracy: 0.6501 - val_loss: 0.6324 - val_accuracy: 0.6507
Epoch 20/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6298 - accuracy: 0.6519 - val_loss: 0.6315 - val_accuracy: 0.6516
Epoch 21/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6287 - accuracy: 0.6540 - val_loss: 0.6299 - val_accuracy: 0.6520
Epoch 22/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6265 - accuracy: 0.6581 - val_loss: 0.6215 - val_accuracy: 0.6678
Epoch 23/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6375 - accuracy: 0.6406 - val_loss: 0.6379 - val_accuracy: 0.6455
Epoch 24/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6354 - accuracy: 0.6429 - val_loss: 0.6391 - val_accuracy: 0.6491
Epoch 25/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6343 - accuracy: 0.6429 - val_loss: 0.6335 - val_accuracy: 0.6475
Epoch 26/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6325 - accuracy: 0.6486 - val_loss: 0.6291 - val_accuracy: 0.6576
Epoch 27/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6299 - accuracy: 0.6600 - val_loss: 0.6277 - val_accuracy: 0.6714
Epoch 28/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6296 - accuracy: 0.6625 - val_loss: 0.7258 - val_accuracy: 0.4691
Epoch 29/100
858/858 [==============================] - 2s 2ms/step - loss: 0.7918 - accuracy: 0.5468 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 30/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 31/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6911 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 32/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6911 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 33/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 34/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 35/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 36/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 37/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 38/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 39/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 40/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6911 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 41/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 42/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 43/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 44/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 45/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 46/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 47/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 48/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 49/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 50/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 51/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 52/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 53/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 54/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 55/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 56/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 57/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6918 - val_accuracy: 0.5325
Epoch 58/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6918 - val_accuracy: 0.5325
Epoch 59/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 60/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 61/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6914 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 62/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5316 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 63/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 64/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 65/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 66/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 67/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 68/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 69/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6917 - val_accuracy: 0.5325
Epoch 70/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6915 - val_accuracy: 0.5325
Epoch 71/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 72/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5317 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 73/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 74/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 75/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 76/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6913 - val_accuracy: 0.5325
Epoch 77/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 78/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 79/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 80/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 81/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 82/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6912 - val_accuracy: 0.5325
Epoch 83/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 84/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 85/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 86/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 87/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6911 - accuracy: 0.5324 - val_loss: 0.6914 - val_accuracy: 0.5325
Epoch 88/100
858/858 [==============================] - 4s 5ms/step - loss: 0.6911 - accuracy: 0.5324 - val_loss: 0.6922 - val_accuracy: 0.5325
Epoch 89/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 90/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6914 - val_accuracy: 0.5325
Epoch 91/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 92/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6911 - val_accuracy: 0.5325
Epoch 93/100
858/858 [==============================] - 3s 4ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6914 - val_accuracy: 0.5325
Epoch 94/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6913 - val_accuracy: 0.5325
Epoch 95/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5324 - val_loss: 0.6916 - val_accuracy: 0.5325
Epoch 96/100
858/858 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 97/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 98/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 99/100
858/858 [==============================] - 3s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325
Epoch 100/100
858/858 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5324 - val_loss: 0.6910 - val_accuracy: 0.5325

In [30]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 1.6455 - accuracy: 0.6948 - 305ms/epoch - 1ms/step
Loss: 1.6455414295196533, Accuracy: 0.6947522163391113

In [31]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(